import type { InventoryItem } from '../types';

export const inventory: InventoryItem[] = [
  { 
    id: "my-cv", 
    type: 'writing', 
    title: 'CV / Resume', 
    icon: 'cv',
    action: 'download',
    componentKey: 'CV',
    downloadPath: '/assets/cv.pdf' // Place your PDF in public/assets/cv.pdf
  },
  
  // Component overlay (About Me)
  { 
    id: 'about-me', 
    type: 'experience', 
    title: 'About Me', 
    icon: 'about-me', 
    action: 'component',
    componentKey: 'AboutMe' 
  },
  { 
    id: 'github', 
    type: 'social', 
    title: 'GitHub', 
    icon: 'github',
    action: 'link',
    link: 'https://github.com/example' 
  },
  { 
    id: 'linkedin', 
    type: 'social', 
    title: 'LinkedIn', 
    icon: 'linkedin',
    action: 'link',
    link: 'https://linkedin.com/in/example' 
  },
  { 
    id: 'x-profile', 
    type: 'social', 
    title: 'X Profile', 
    icon: 'x',
    action: 'link',
    link: 'https://x.com/example' 
  },
  { id: 'software-projects', type: 'project', title: 'Software Projects', icon: 'software' },
  { 
    id: 'portfolio-repo', 
    type: 'project', 
    title: 'Portfolio Source', 
    icon: 'simon-os-github', 
    action: 'link',
    link: 'https://github.com/splieseis/simon-os' 
  },
  { id: 'work-projects', type: 'project', title: 'Work Projects', icon: 'work' },
  { id: 'side-hustles', type: 'project', title: 'Side Hustles', icon: 'side-hustles' },
  { id: 'contact', type: 'social', title: 'Contact', icon: 'contact' },
  { id: 'mini-apps', type: 'mini-app', title: 'Mini Apps', icon: 'apps' },
  { id: 'old-projects-museum', type: 'project', title: 'Old Projects Museum', icon: 'museum' },
  { id: 'startups', type: 'project', title: 'Startups', icon: 'rocket' },
  { id: 'bookmarks', type: 'writing', title: 'Bookmarks', icon: 'bookmarks' },
  { id: 'random-thoughts', type: 'writing', title: 'Random Thoughts', icon: 'thoughts' },
  { id: 'affiliate-links', type: 'social', title: 'Affiliate Links', icon: 'affiliate-link' },
  { id: 'settings', type: 'project', title: 'Settings', icon: 'settings' },
  { 
    id: 'json-tool', 
    type: 'mini-app', 
    title: 'JSON Formatter', 
    icon: 'json', 
    action: 'component',
    componentKey: 'JsonFormatter' 
  },
  { id: 'newsletter-archive', type: 'writing', title: 'Newsletter Archive', icon: 'news' },
  // { id: 'blog-posts', type: 'writing', title: 'Blog Posts', icon: 'book-open' },
  // { id: 'free-tools', type: 'mini-app', title: 'Free Tools', icon: 'terminal' },
  // { id: 'recipes', type: 'recipe', title: 'Recipes', icon: 'chef-hat' },
  // { id: 'new-blog-ai-ethics', type: 'writing', title: 'New Blog: AI Ethics', icon: 'file-text' },
  // { id: 'project-update-codecraft', type: 'project', title: 'Project Update: CodeCraft', icon: 'code' },
  // { id: 'recipe-pixel-chili', type: 'recipe', title: 'Recipe: Pixel Chili', icon: 'chef-hat' },
  // { id: 'thought-future-of-tech', type: 'writing', title: 'Thought: Future of Tech', icon: 'lightbulb' },
  // { id: 'about-me-duplicate', type: 'experience', title: 'About Me', icon: 'user' },
  // { id: 'favourite-ai-tools', type: 'mini-app', title: 'Favourite AI Tools', icon: 'code' },
  // { id: 'ai-prompts', type: 'mini-app', title: 'AI Prompts', icon: 'lightbulb' },
  // { id: 'personal-life-milestones', type: 'experience', title: 'Personal Life Milestones', icon: 'user' },
  // { id: 'portfolio-site', type: 'project', title: 'Portfolio Site', icon: 'code' },
  // { id: 'e-commerce-platform', type: 'project', title: 'E-Commerce Platform', icon: 'briefcase' },
  // { id: 'color-picker', type: 'mini-app', title: 'Color Picker', icon: 'terminal' },
  // { id: 'markdown-editor', type: 'mini-app', title: 'Markdown Editor', icon: 'file-text' },
  // { id: 'breakfast-ideas', type: 'recipe', title: 'Breakfast Ideas', icon: 'chef-hat' },
  // { id: 'tech-review-m3-chip', type: 'writing', title: 'Tech Review: M3 Chip', icon: 'book-open' },
  // { id: 'mobile-app', type: 'project', title: 'Mobile App', icon: 'rocket' },
  // { id: 'api-service', type: 'project', title: 'API Service', icon: 'code' },
  // { id: 'base64-encoder', type: 'mini-app', title: 'Base64 Encoder', icon: 'terminal' },
  // { id: 'travel-blog', type: 'writing', title: 'Travel Blog', icon: 'book-open' },
  // { id: 'design-system', type: 'project', title: 'Design System', icon: 'folder' },
  // { id: 'qr-generator', type: 'mini-app', title: 'QR Generator', icon: 'terminal' },
  // { id: 'quick-dinners', type: 'recipe', title: 'Quick Dinners', icon: 'chef-hat' },
  // { id: 'productivity-tips', type: 'writing', title: 'Productivity Tips', icon: 'lightbulb' },
  // { id: 'chrome-extension', type: 'project', title: 'Chrome Extension', icon: 'code' },
  // { id: 'career-journey', type: 'experience', title: 'Career Journey', icon: 'user' },
  // { id: 'open-source-contrib', type: 'project', title: 'Open Source Contrib', icon: 'github' },
  // { id: 'uuid-generator', type: 'mini-app', title: 'UUID Generator', icon: 'terminal' },
  // { id: 'saas-dashboard', type: 'project', title: 'SaaS Dashboard', icon: 'rocket' },
];
